const productData =
 [
    {
      id: 1,
      name: "Chinese Cabbage",
      description: "Fresh Chinese cabbage, perfect for salads and soups. Rich in vitamins and a great addition to your healthy diet.",
      image: "/public (feature_product)/Chinese cabbage.png",
      price: "$12.00",
      discount: "10%",
      category: "Vegetables",
      stock: 100,
      brand: "EcoFresh",
      tag: ["Organic", "Healthy"],
      off: "10% OFF",
      weight: "200g",
      color: "Green",
      type: "Fresh",
    },
    {
      id: 2,
      name: "Green Lettuce",
      description: "Crisp, fresh green lettuce for your daily salads. Rich in fiber and essential nutrients.",
      image: "/public/feature_product/Green Lettuce.png",
      price: "$9.00",
      discount: "5%",
      category: "Vegetables",
      stock: 150,
      brand: "EcoFresh",
      tag: ["Organic", "Fresh"],
      off: "5% OFF",
      weight: "250g",
      color: "Green",
      type: "Fresh",
    },
    {
      id: 3,
      name: "Fresh Indian Malta",
      description: "Fresh, juicy Indian Malta for a refreshing taste. Perfect for juices or a healthy snack.",
      image: "/public/feature_product/Fresh Indian Malta.png",
      price: "$20.00",
      discount: "15%",
      category: "Fruit",
      stock: 120,
      brand: "EcoFresh",
      tag: ["Fresh", "Organic"],
      off: "15% OFF",
      weight: "300g",
      color: "Orange",
      type: "Fresh",
    },
    {
      id: 4,
      name: "Green Apple",
      description: "Fresh green apples, great for a healthy snack. Packed with nutrients and perfect for weight loss.",
      image: "/public/feature_product/Green Apple.png",
      price: "$14.99",
      discount: "5%",
      category: "Fruit",
      stock: 200,
      brand: "EcoFresh",
      tag: ["Organic", "Healthy"],
      off: "5% OFF",
      weight: "250g",
      color: "Green",
      type: "Fresh",
    },
    {
      id: 5,
      name: "Eggplant",
      description: "Fresh eggplant, perfect for grilling or frying. Full of antioxidants and a great source of fiber.",
      image: "/public/feature_product/Eggplant.png",
      price: "$34.00",
      discount: "20%",
      category: "Vegetables",
      stock: 80,
      brand: "EcoFresh",
      tag: ["Organic", "Vegetarian"],
      off: "20% OFF",
      weight: "300g",
      color: "Purple",
      type: "Fresh",
    },
    {
          id: 6,
          name: "Big Potatoes",
          description: "Large, fresh potatoes for cooking and frying.",
          image: "/public/hot_deals/Big Potatoes.png",
          price: "$20.00",
          discount: "10%",
          category: "Vegetables",
          stock: 150,
          brand: "EcoFresh",
          tag: ["Organic", "Fresh"],
          off: "10% OFF",
          weight: "500g",
          color: "Brown",
          type: "Fresh",
        },
        {
          id: 7,
          name: "Corn",
          description: "Sweet, fresh corn on the cob.",
          image: "/public/hot_deals/Corn.png",
          price: "$12.00",
          discount: "15%",
          category: "Vegetables",
          stock: 100,
          brand: "EcoFresh",
          tag: ["Organic", "Fresh"],
          off: "15% OFF",
          weight: "250g",
          color: "Yellow",
          type: "Fresh",
        },
        {
          id: 8,
          name: "Fresh Cauliflower",
          description: "Organic cauliflower, perfect for stews and salads.",
          image: "/public/hot_deals/Fresh Cauliflower.png",
          price: "$12.00",
          discount: "10%",
          category: "Vegetables",
          stock: 80,
          brand: "EcoFresh",
          tag: ["Organic", "Healthy"],
          off: "10% OFF",
          weight: "400g",
          color: "White",
          type: "Fresh",
        },
        {
          id: 9,
          name: "Green Capsicum",
          description: "Fresh, organic green capsicum, great for salads and cooking.",
          image: "/public/hot_deals/Green Capsicum.png",
          price: "$9.00",
          discount: "5%",
          category: "Vegetables",
          stock: 120,
          brand: "EcoFresh",
          tag: ["Organic", "Fresh"],
          off: "5% OFF",
          weight: "200g",
          color: "Green",
          type: "Fresh",
        },
        {
          id: 10,
          name: "Green Chili",
          description: "Fresh green chili for a spicy kick in your dishes.",
          image: "/public/hot_deals/Green Chili.png",
          price: "$34.00",
          discount: "20%",
          category: "Vegetables",
          stock: 90,
          brand: "EcoFresh",
          tag: ["Organic", "Spicy"],
          off: "20% OFF",
          weight: "150g",
          color: "Green",
          type: "Fresh",
        },
        {
          id: 11,
          name: "Red Chili",
          description: "Fresh red chili for all your cooking needs.",
          image: "/public/hot_deals/Red Chili.png",
          price: "$12.00",
          discount: "15%",
          category: "Vegetables",
          stock: 70,
          brand: "EcoFresh",
          tag: ["Organic", "Spicy"],
          off: "15% OFF",
          weight: "150g",
          color: "Red",
          type: "Fresh",
        },
        {
          id: 12,
          name: "Fresh Indian Malta",
          description: "Fresh, organic Indian Malta.",
          image: "/public/hot_deals/Fresh Indian Malta.png",
          price: "$20.00",
          discount: "10%",
          category: "Fruit",
          stock: 110,
          brand: "EcoFresh",
          tag: ["Organic", "Fresh"],
          off: "10% OFF",
          weight: "300g",
          color: "Orange",
          type: "Fresh",
        },
        {
          id: 13,
          name: "Surjapur Mango",
          description: "Sweet, fresh mangoes from Surjapur.",
          image: "/public/hot_deals/Surjapur Mango.png",
          price: "$34.00",
          discount: "15%",
          category: "Fruit",
          stock: 150,
          brand: "EcoFresh",
          tag: ["Organic", "Fresh"],
          off: "15% OFF",
          weight: "500g",
          color: "Yellow",
          type: "Fresh",
        },
        {
          id: 14,
          name: "Red Tomatoes",
          description: "Fresh red tomatoes for cooking.",
          image: "/public/hot_deals/Red Tomatoes.png",
          price: "$15.00",
          discount: "10%",
          category: "Vegetables",
        stock: 200,
       brand: "EcoFresh",
      tag: ["Organic", "Fresh"],
      off: "10% OFF",
      weight: "400g",
      color: "Red",
      type: "Fresh",
        },
        {
            id: 15,
            name: "Baking Needs",
            description: "Essential items for your baking needs.",
            image: "/public/popular_category/Baking Needs.png",
            price: "$18.99",
            discount: "5%",
            category: "Baking",
            stock: 90,
            brand: "Bakers Delight",
            tag: ["Baking", "Organic"],
            off: "5% OFF",
            weight: "1kg",
            color: "Brown",
            type: "Baking",
          },
          {
            id: 16,
            name: "Beauty & Health",
            description: "Beauty and health products for your well-being.",
            image: "/public/popular_category/Beauty & Health.png",
            price: "$35.99",
            discount: "10%",
            category: "Health",
            stock: 120,
            brand: "BeautyGlow",
            tag: ["Health", "Organic"],
            off: "10% OFF",
            weight: "300g",
            color: "Pink",
            type: "Health",
          },
          {
            id: 17,
            name: "Essential Oils",
            description: "Pure, natural essential oils for relaxation and healing.",
            image: "/public/popular_category/Essential Oils.png",
            price: "$22.00",
            discount: "15%",
            category: "Health",
            stock: 100,
            brand: "Natural Essence",
            tag: ["Organic", "Aromatherapy"],
            off: "15% OFF",
            weight: "100g",
            color: "Clear",
            type: "Health",
          },
          {
            id: 18,
            name: "Home Decor",
            description: "Decorative items to beautify your home.",
            image: "/public/popular_category/Home Decor.png",
            price: "$50.00",
            discount: "20%",
            category: "Decor",
            stock: 200,
            brand: "EcoHome",
            tag: ["Stylish", "Eco-friendly"],
            off: "20% OFF",
            weight: "1.5kg",
            color: "Multi",
            type: "Decor",
          },
          {
            id: 19,
            name: "Organic Teas",
            description: "Relaxing and refreshing organic teas for every taste.",
            image: "/public/popular_category/Organic Teas.png",
            price: "$15.00",
            discount: "10%",
            category: "Beverages",
            stock: 250,
            brand: "PureLeaf",
            tag: ["Organic", "Healthy"],
            off: "10% OFF",
            weight: "200g",
            color: "Green",
            type: "Beverages",
          },
          {
            id: 20,
            name: "Organic Honey",
            description: "Pure, organic honey for a healthy lifestyle.",
            image: "/public/popular_category/Organic Honey.png",
            price: "$20.00",
            discount: "15%",
            category: "Food",
            stock: 150,
            brand: "BeeGold",
            tag: ["Organic", "Sweet"],
            off: "15% OFF",
            weight: "500g",
            color: "Golden",
            type: "Food",
          },
          {
            id: 21,
            name: "Pet Care",
            description: "Everything your pet needs to stay happy and healthy.",
            image: "/public/popular_category/Pet Care.png",
            price: "$25.00",
            discount: "5%",
            category: "Pets",
            stock: 80,
            brand: "HappyPets",
            tag: ["Pet-friendly", "Healthy"],
            off: "5% OFF",
            weight: "300g",
            color: "Multi",
            type: "Pet Care",
          },
          {
            id: 22,
            name: "Fitness Equipment",
            description: "High-quality fitness equipment for home workouts.",
            image: "/public/popular_category/Fitness Equipment.png",
            price: "$150.00",
            discount: "10%",
            category: "Sports",
            stock: 60,
            brand: "FitPro",
            tag: ["Fitness", "Gym"],
            off: "10% OFF",
            weight: "5kg",
            color: "Black",
            type: "Sports",
          },
          {
            id: 23,
            name: "Kitchen Essentials",
            description: "Everything you need for a well-equipped kitchen.",
            image: "/public/popular_category/Kitchen Essentials.png",
            price: "$40.00",
            discount: "15%",
            category: "Home",
            stock: 90,
            brand: "KitchenWare",
            tag: ["Essential", "Home"],
            off: "15% OFF",
            weight: "2kg",
            color: "Silver",
            type: "Home",
          },
          {
            id: 24,
            name: "Outdoor Gear",
            description: "Durable and practical gear for outdoor activities.",
            image: "/public/popular_category/Outdoor Gear.png",
            price: "$75.00",
            discount: "20%",
            category: "Outdoor",
            stock: 80,
            brand: "TrekGear",
            tag: ["Outdoor", "Adventure"],
            off: "20% OFF",
            weight: "1.5kg",
            color: "Green",
            type: "Outdoor",
          },
          {
            id: 25,
            name: "Tech Gadgets",
            description: "The latest and best tech gadgets for your lifestyle.",
            image: "/public/popular_category/Tech Gadgets.png",
            price: "$100.00",
            discount: "10%",
            category: "Electronics",
            stock: 120,
            brand: "TechMaster",
            tag: ["Gadgets", "Tech"],
            off: "10% OFF",
            weight: "500g",
            color: "Black",
            type: "Electronics",
          },
          {
            id: 26,
            name: "Smartphones",
            description: "Latest smartphones with advanced features.",
            image: "/public/popular_category/Smartphones.png",
            price: "$300.00",
            discount: "5%",
            category: "Electronics",
            stock: 150,
            brand: "PhoneTech",
            tag: ["Tech", "Smartphone"],
            off: "5% OFF",
            weight: "200g",
            color: "Silver",
            type: "Electronics",
          },
          {
            id: 27,
            name: "Luxury Watches",
            description: "Elegant and stylish luxury watches for every occasion.",
            image: "/public/popular_category/Luxury Watches.png",
            price: "$250.00",
            discount: "10%",
            category: "Fashion",
            stock: 50,
            brand: "Elegance",
            tag: ["Luxury", "Fashion"],
            off: "10% OFF",
            weight: "300g",
            color: "Gold",
            type: "Fashion",
          },
          {
            id: 28,
            name: "Luggage Bags",
            description: "Travel in style with our premium luggage bags.",
            image: "/public/popular_category/Luggage Bags.png",
            price: "$80.00",
            discount: "15%",
            category: "Travel",
            stock: 90,
            brand: "TravelMate",
            tag: ["Travel", "Luxury"],
            off: "15% OFF",
            weight: "2kg",
            color: "Black",
            type: "Travel",
          },
          {
            id: 29,
            name: "Green Apple",
            description: "Fresh green apples, perfect for a healthy snack. Packed with nutrients and perfect for weight loss.",
            image: "/public/popular_product/Green Apple.png",
            price: "$14.99",
            discount: "5%",
            category: "Fruit",
            stock: 80,
            brand: "EcoFresh",
            tag: ["Organic", "Healthy"],
            off: "5% OFF",
            weight: "250g",
            color: "Green",
            type: "Fresh",
          },
          {
            id: 30,
            name: "Fresh Cauliflower",
            description: "Fresh organic cauliflower, perfect for cooking. Low in calories, high in fiber.",
            image: "/public/popular_product/Fresh Cauliflower.png",
            price: "$12.00",
            discount: "10%",
            category: "Vegetables",
            stock: 100,
            brand: "EcoFresh",
            tag: ["Organic", "Healthy"],
            off: "10% OFF",
            weight: "500g",
            color: "White",
            type: "Fresh",
          },
          {
            id: 31,
            name: "Red Tomatoes",
            description: "Fresh, ripe red tomatoes, perfect for cooking and salads.",
            image: "/public/popular_product/Red Tomatoes.png",
            price: "$8.00",
            discount: "5%",
            category: "Vegetables",
            stock: 150,
            brand: "EcoFresh",
            tag: ["Organic", "Fresh"],
            off: "5% OFF",
            weight: "400g",
            color: "Red",
            type: "Fresh",
          },
          {
            id: 32,
            name: "Green Capsicum",
            description: "Organic green capsicum, great for cooking and adding crunch to salads.",
            image: "/public/popular_product/Green Capsicum.png",
            price: "$9.00",
            discount: "5%",
            category: "Vegetables",
            stock: 120,
            brand: "EcoFresh",
            tag: ["Organic", "Fresh"],
            off: "5% OFF",
            weight: "200g",
            color: "Green",
            type: "Fresh",
          },
          {
            id: 33,
            name: "Big Potatoes",
            description: "Fresh, large potatoes, perfect for making fries or mashed potatoes.",
            image: "/public/popular_product/Big Potatoes.png",
            price: "$20.00",
            discount: "10%",
            category: "Vegetables",
            stock: 180,
            brand: "EcoFresh",
            tag: ["Organic", "Fresh"],
            off: "10% OFF",
            weight: "500g",
            color: "Brown",
            type: "Fresh",
          },
          {
            id: 34,
            name: "Eggplant",
            description: "Fresh eggplant, ideal for grilling or frying. Packed with antioxidants.",
            image: "/public/popular_product/Eggplant.png",
            price: "$34.00",
            discount: "15%",
            category: "Vegetables",
            stock: 70,
            brand: "EcoFresh",
            tag: ["Organic", "Vegetarian"],
            off: "15% OFF",
            weight: "250g",
            color: "Purple",
            type: "Fresh",
          },
          {
            id: 35,
            name: "Fresh Indian Malta",
            description: "Fresh Indian Malta, known for its sweetness and juiciness.",
            image: "/public/popular_product/Fresh Indian Malta.png",
            price: "$18.00",
            discount: "10%",
            category: "Fruit",
            stock: 140,
            brand: "EcoFresh",
            tag: ["Fresh", "Juicy"],
            off: "10% OFF",
            weight: "350g",
            color: "Orange",
            type: "Fresh",
          },
          {
            id: 36,
            name: "Surjapur Mango",
            description: "Delicious and sweet Surjapur mangoes, perfect for smoothies and desserts.",
            image: "/public/popular_product/Surjapur Mango.png",
            price: "$30.00",
            discount: "20%",
            category: "Fruit",
            stock: 60,
            brand: "EcoFresh",
            tag: ["Fresh", "Tropical"],
            off: "20% OFF",
            weight: "500g",
            color: "Yellow",
            type: "Fresh",
          },
          {
            id: 37,
            name: "Red Chili",
            description: "Spicy red chili, perfect for adding heat to your dishes.",
            image: "/public/popular_product/Red Chili.png",
            price: "$12.00",
            discount: "15%",
            category: "Vegetables",
            stock: 100,
            brand: "EcoFresh",
            tag: ["Spicy", "Organic"],
            off: "15% OFF",
            weight: "100g",
            color: "Red",
            type: "Fresh",
          }
    
    
  ];
  